In [149]:
import torch
from torch import nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.0


In [150]:
# Create tensor

TENSOR = torch.tensor([[[1, 2], [4, 5]], [[9, 8], [1,2]]])
TENSOR.shape


torch.Size([2, 2, 2])

In [151]:
torch.rand(3, 4)

tensor([[0.1049, 0.9564, 0.4883, 0.5452],
        [0.5629, 0.3676, 0.9494, 0.5594],
        [0.2729, 0.3658, 0.5597, 0.3000]])

In [152]:
random_image_tensor = torch.rand(64,64,3)
random_image_tensor

tensor([[[0.8534, 0.2759, 0.1201],
         [0.7756, 0.0765, 0.0981],
         [0.4989, 0.3220, 0.3267],
         ...,
         [0.5762, 0.2185, 0.6940],
         [0.7367, 0.9335, 0.0244],
         [0.7654, 0.4948, 0.5348]],

        [[0.2726, 0.4459, 0.2408],
         [0.1418, 0.7263, 0.2561],
         [0.1298, 0.9547, 0.8891],
         ...,
         [0.8546, 0.4680, 0.4388],
         [0.3059, 0.6959, 0.9865],
         [0.8519, 0.2704, 0.7750]],

        [[0.0153, 0.2735, 0.9630],
         [0.2687, 0.4720, 0.5725],
         [0.5431, 0.9533, 0.6479],
         ...,
         [0.5214, 0.7043, 0.9118],
         [0.4554, 0.4927, 0.9402],
         [0.6482, 0.5688, 0.4067]],

        ...,

        [[0.6108, 0.4965, 0.8596],
         [0.1715, 0.5787, 0.2392],
         [0.8625, 0.7525, 0.9358],
         ...,
         [0.8723, 0.9594, 0.1981],
         [0.4518, 0.9372, 0.0369],
         [0.7032, 0.6806, 0.2159]],

        [[0.1551, 0.6245, 0.2804],
         [0.1396, 0.1321, 0.1663],
         [0.

In [153]:
list = torch.arange(1,11,1)
list


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
copy = torch.ones_like(list)
copy

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [155]:
shape = torch.tensor(data=[1,2,3,4], dtype=torch.int64, device=None, requires_grad=False)

def tensor_info(tensor):
    print(tensor)
    print(f"Data type: {tensor.dtype}")
    print(f"Shape: {tensor.shape}")
    print(f"Device runs on: {tensor.device}")

tensor_info(shape)

tensor([1, 2, 3, 4])
Data type: torch.int64
Shape: torch.Size([4])
Device runs on: cpu


In [156]:
tensor1 = torch.tensor(
    [
    [1,2,3,8],
    [4,5,6,7]
    ]
                       )

tensor2 = torch.tensor(
    [
    [1,2],
    [3,4],
    [5,6],
    [2,9]
    ]
)

product = torch.matmul(tensor1, tensor2)

In [157]:
print(product)
product.T # Transverse the matrix

tensor([[ 38, 100],
        [ 63, 127]])


tensor([[ 38,  63],
        [100, 127]])

In [158]:
# Tensor aggregation

x = torch.arange(0, 20, 1)
print(x)
print(f"Max: {x.max()}")
print(f"Min: {x.min()}")
print(f"Sum: {x.sum()}")
print(f"Median: {x.median()}")
print(f"Mean: {x.type(torch.float32).mean()}") # Have to convert the tensor to float first

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
Max: 19
Min: 0
Sum: 190
Median: 9
Mean: 9.5


In [159]:
example = torch.arange(1, 11, 1)
print(example)

# Rashape tensor to a dimention
torch.reshape(example, (1,5,2))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]])

In [160]:
example2 = example.view(1,10)
example2[:,0] = 0 # change the value at index 0 of example2 changes example 2 because of the view() function
example

tensor([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [161]:
a = torch.tensor(
        [4,5,6]
                )

b = torch.tensor(
        [4,5,6]
                )
print(torch.hstack((a,b)))
print(torch.stack((a,b)))

print(torch.stack((a,b), dim=0))
print(torch.stack((a,b), dim=1))

tensor([4, 5, 6, 4, 5, 6])
tensor([[4, 5, 6],
        [4, 5, 6]])
tensor([[4, 5, 6],
        [4, 5, 6]])
tensor([[4, 4],
        [5, 5],
        [6, 6]])


In [162]:
x = torch.tensor([
    [1,2],
    [3,4]
])
print(x)
print(x.shape)

x=x.unsqueeze(dim=1)
print(x)
print(x.shape)

x=x.squeeze()
print(x)
print(x.shape)


tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
tensor([[[1, 2]],

        [[3, 4]]])
torch.Size([2, 1, 2])
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [163]:
x = torch.tensor([
    [1,2,5],
    [3,4,6]
])

x = x.unsqueeze(dim=1)
print(x, x.shape)
x=x.permute(1,2,0)  # permute manipulate the dimentions by change their orders
print(x, x.shape)

tensor([[[1, 2, 5]],

        [[3, 4, 6]]]) torch.Size([2, 1, 3])
tensor([[[1, 3],
         [2, 4],
         [5, 6]]]) torch.Size([1, 3, 2])


In [164]:
# Convert Numpy array to pytorch tensor

arr = np.arange(1,11,1)
print(arr)

arr_to_tensor = torch.from_numpy(arr)
print(arr_to_tensor)


[ 1  2  3  4  5  6  7  8  9 10]
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)


In [165]:
# Reproducibility

# Set up reproduciable random tensors

RANDOM_SEED = 31415926

torch.manual_seed(RANDOM_SEED)
one = torch.rand(3,3)
print(one)


torch.manual_seed(RANDOM_SEED)
two = torch.rand(3,3)
print(two)
print(one==two)


tensor([[0.4814, 0.5225, 0.9889],
        [0.4548, 0.5006, 0.5227],
        [0.9097, 0.0697, 0.0596]])
tensor([[0.4814, 0.5225, 0.9889],
        [0.4548, 0.5006, 0.5227],
        [0.9097, 0.0697, 0.0596]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
